version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./webapp/sql:/docker-entrypoint-initdb.d
      # - ./webapp/sql/conf:/etc/mysql/conf.d
      - ./datadir:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: ./webapp/ruby
    command: bash -c "cd webapp/ruby && bundle exec rackup -p 8000 -o 0.0.0.0"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
    ports:
      - 8000:8000
    depends_on:
      - db
